# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chamiloApp' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 5.15.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chamiloApp

  

  platform :ios, '9.0'


  target 'chamiloAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chamiloApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chamiloApp-tvOS

  target 'chamiloApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
