# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chamiloApp' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 5.15.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chamiloApp

  

  platform :ios, '9.0'


end

